version: '3.1'

services:
  democicd:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/demo-cicd.local
    container_name: c-democicd
    restart: always
    extra_hosts:
      - "demo-cicd.local:127.0.0.1"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/
      APACHE_DOCUMENT_DEMOCICD: /var/www/demo-cicd.local/public
      APP_ENV: local

networks:
  default:
    name: docker-network
    external: true