version: '3.1'

services:
  web:
    build: ./docker/php
    ports:
      - 8000:80
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
      APP_ENV: local
    container_name: web
    restart: always

networks:
  default:
    name: docker-network
    external: true